=== georgelele1/ITEC4020G4/src/main/webapp/xml/product.dtd
<!ELEMENT ProductList (product)*>
        <!ELEMENT product (productID|productname|managerid|img)*>
        <!ELEMENT productID (#PCDATA)>
        <!ELEMENT productname (#PCDATA)>
        <!ELEMENT managerid (#PCDATA)>
         <!ELEMENT img (#PCDATA)>

=== georgelele1/ITEC4020G4/src/main/webapp/xml/product.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ProductList SYSTEM "product.dtd">
<ProductList>
    <product>
        <productID>00</productID>
        <productname>Hardware</productname>
        <managerid>Mohamad</managerid>
        <img>pc.JPG</img>
    </product>
    <product>
        <productID>01</productID>
        <productname>Software</productname>
        <managerid>Yanbo</managerid>
        <img>ram.JPG</img>
    </product>
    <product>
        <productID>02</productID>
        <productname>PC accessory</productname>
        <managerid>Noor</managerid>
        <img>cooler.JPG</img>
    </product>
    <product>
        <productID>03</productID>
        <productname>MIC</productname>
        <managerid>test</managerid>
        <img>cooler.JPG</img>
    </product>
    <product>
        <productID>03</productID>
        <productname>TV</productname>
        <managerid>Hasham</managerid>
        <img>cooler.JPG</img>
    </product>
    <product>
        <productID>03</productID>
        <productname>Playstation</productname>
        <managerid>Natnael</managerid>
        <img>cooler.JPG</img>
    </product>
</ProductList>
